[project]
name = "finance-sheets"
version = "0.1.0"
description = "Bot do Telegram para gerenciamento financeiro pessoal, integrado ao Google Sheets e com processamento inteligente de transações usando IA"
readme = "README.md"
authors = [
    { name = "Gabriel Guerra", email = "gabrielcake9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.16.0",
    "gspread>=6.2.1",
    "python-dateutil>=2.9.0.post0",
    "python-telegram-bot>=22.8",
]

[project.scripts]
finance-sheets = "finance_sheets:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyngrok>=8.1.2",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.52.0",
]
